description: Master HEAT template for Server Configuration
heat_template_version: '2015-04-30'

parameters:
  branch_rsConfigs: {default: staging, type: string}
  build_count: {default: 1, description: number of devices to build, type: string}
  flavor:
      constraints:
      -   allowed_values: [1 GB Performance, 2 GB Performance, 4 GB Performance,
              8 GB Performance, 15 GB Performance, 1 GB General Purpose v1, 2 GB
                  General Purpose v1, 4 GB General Purpose v1, 8 GB General Purpose
                  v1]
          description: must be a valid Rackspace Cloud Server flavor.
      default: 4 GB Performance
      description: Rackspace Cloud Server flavor
      type: string
  git_Oauthtoken: {type: string}
  git_username: {type: string}
  web_server_name: {default: WebFarm1, description: base name for the web server instances, type: string}

  image:
      constraints:
      -   allowed_values: [Windows Server 2012, Windows Server 2012 R2]
      default: Windows Server 2012 R2
      description: Rackspace Cloud Server image name
      type: string
  main_Repo: {default: DDI_RSConfigs, description: provisioning repo branch, type: string}
  prov_Branch: {default: v2.0.0, description: provisioning repo branch, type: string}
  pullserver_hostname:
      constraints:
      -   length: {max: 15, min: 1}
      default: PULLServer
      description: Windows Server Name
      type: string
  rs_apikey: {description: Rackspace Cloud APIKey, type: string}
  rs_username: {description: Rackspace Cloud Username, type: string}
  stack_guid: {default: 0, description: GUID for this stack, type: string}
resources:
  webnodes:
    type: test.yml
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      branch_rsConfigs: {get_param: branch_rsConfigs}
      build_count: {get_param: build_count}
      git_Oauthtoken: {get_param: git_Oauthtoken}
      git_username: {get_param: git_username}
      web_server_name: {get_param: web_server_name}
      main_Repo: {get_param: main_Repo}
      prov_Branch: {get_param: prov_Branch}
      rs_apikey: {get_param: rs_apikey}
      rs_username: {get_param: rs_username}
      stack_guid: {get_param: stack_guid}